### ISSUE TITLE
[SDesc] Add component to show money

### ISSUE THREAD

**Issue by NozomuIkuta** [globalbrain/sefirot#461]
The name will `SDescMoney` which renders Money value like `¥ 23,456 CNY`.
Maybe extended version of `SDescNumber`?

**Comment by kiaking** [comment]
I always wanted this too. And good point about whether we extend other base desc value to do this... 🤔 

Need to come up with solid design first. I'll think about it. But at the end, I think it wouldn't be named like `<SDescMoney>` in Sefirot, because it will be hard to define Money model in Sefirot. That depends too much on use cases.

In stead, I think it would be better to have more generic component which can have prefix, or suffix, and then we can use that component in the apps to display anything.
