### ISSUE TITLE
Enhancement: Add select and multi select components to the form

### ISSUE THREAD

**Issue by pjsaran** [globalbrain/sefirot#6]
We should add select and multiselect components which is basic to any form.

**Comment by kiaking** [comment]
@pjsaran Thank you so much for the feedback! Definitely, we should have select and multiselect input. I'll be working on to it 👍

**Comment by kiaking** [comment]
`SInputSelect` component is added at Sefirot 0.7.0 🎉  
https://github.com/globalbrain/sefirot/releases/tag/v0.7.0

@pjsaran Thank you so much for the request! One note, though. I didn't implement the multiselect component. Since we believe multiselect input dialog is not that perfect, especially when using in a mobile device. I would suggest considering using checkboxes or other types of list selection component for multi selectable items.
